version: '3.9'
services:
  order-service:
    build: .
    container_name: order-service
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: postgres:16-alpine
    container_name: order-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: order-rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  postgres_data:
